### ISSUE TITLE
Инстанцирование объекта 

### ISSUE THREAD

**Issue by programmwriter** [shylskii/aviasales_v3#1]
https://github.com/shylskii/aviasales_v3/blob/383526b84cb7ac1c4c9859e6d65653d3c779ac43/src/components/app/app.js#L19

Инициализацию объекта лучше выносить за пределы компонента или класть в ref, иначе он будет пересоздаваться при каждом ререндере. Я вижу ты выбрал вариант с рекурсией в компоненте, советую в следующий раз отказаться от такой реализации, что бы не инициировать сервис в компоненте и не передавать методы в экшны.

**Comment by shylskii** [comment]
инициализация вынесена за пределы компонента
