### ISSUE TITLE
Лишняя логика

### ISSUE THREAD

**Issue by programmwriter** [shylskii/aviasales_v3#3]
https://github.com/shylskii/aviasales_v3/blob/383526b84cb7ac1c4c9859e6d65653d3c779ac43/src/components/app/app.js#L22

1. Смотри эта функция не имеет отношения к компоненту app как и кнопка которая её вызывает. Лучше перенести эту логику в компонент который рендерить тикеты. И можно просто диспатчить экшн прям из атрибута onClick не создавай пустых функций
2. Сам Экшн не правильно построен, зачем ты передаешь ему эти параметры? количество билетов и их увеличение нужно делать в редюссере. А updaterForSort я вообще не понял для чего, вижу как он меняется но на нем не завязана логика. Смотрится тоже как лишний. 
3. Из за этой лишней логики компонент перегружен лишними пропсами и лишними перерендерами, надо стараться сводить к минимуму перерендеры корневого компонента.

**Comment by shylskii** [comment]
исправлено
