### ISSUE TITLE
Придерживайся одной реализации

### ISSUE THREAD

**Issue by programmwriter** [shylskii/aviasales_v3#5]
https://github.com/shylskii/aviasales_v3/blob/383526b84cb7ac1c4c9859e6d65653d3c779ac43/src/components/app/app.js#L38

Если ты инициировал сервис в компоненте и делаешь запросы билетов в компоненте, то и запрос id тоже делай в компоненте а в экшн передавай только сам id. Передавать метод сервиса не очень хорошая идея,

**Comment by shylskii** [comment]
исправлено
